---
# Delete Host using Satellite
- name: Delete hosts from specified Satellte/Foreman hostgroups
  hosts: all
  gather_facts: false

  tasks:
  - name: "Delete the host"
    include_tasks: tasks/delete_host.yml